### ISSUE TITLE
OnlySpot waiting status promise

### ISSUE THREAD

**Issue by gnomefin** [NextChapterSoftware/ec2-action-builder#15]
## Overview
I was trying to privision a spot instance it works, however, it is always saying "Waiting..." in github action.

<img width="1206" alt="image" src="https://github.com/NextChapterSoftware/ec2-action-builder/assets/105913725/52f799e8-9846-4f5d-ba04-9ded16563128">
<img width="1006" alt="image" src="https://github.com/NextChapterSoftware/ec2-action-builder/assets/105913725/33647970-982b-41d5-86fa-5feff3539971">

Is there any caveat I have missed?

```
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: NextChapterSoftware/ec2-action-builder@v1
        with:
          github_token: ${{ steps.get-key-3.outputs.GITHUB_TOKEN }}
          aws_access_key_id: ${{ steps.get-key-3.outputs.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ steps.get-key-3.outputs.AWS_SECRET_ACCESS_KEY }}
          aws_region: "ap-southeast-1"
          ec2_instance_type: t3.large
          ec2_ami_id: ami-0be48b687295f8bd6
          ec2_subnet_id: "subnet-0658e74202c95b2a1"
          ec2_security_group_id: "sg-0ecd33647e49f0518"
          ec2_instance_ttl: 40                # Optional (default is 60 minutes)
          ec2_spot_instance_strategy: SpotOnly    # Other options are: SpotOnly, BestEffort, MaxPerformance 
```

## Expectation
It will proceed to the next job.
